// ── Mai Hoa Interpreter Tests — Epic 3 ────────────────────────
// Comprehensive tests for US_MH_06 (Ngũ Hành Interaction),
// US_MH_07 (Temporal Influence), US_MH_08 (Hexagram Meaning Lookup),
// and the full interpretation orchestrator.

import { beforeAll } from 'vitest';
import {
    getElementInteraction,
    assessTheDung,
    getSeasonFromLunarMonth,
    getElementStrength,
    describeTemporalInfluence,
    getHexagramMeaning,
    interpretDivination,
} from '../../src/utils/maiHoaInterpreter';

import {
    performTimeBasedDivination,
    performNumberBasedDivination,
    ensureHexagramsLoaded,
} from '../../src/utils/maiHoaEngine';

beforeAll(async () => {
    await ensureHexagramsLoaded();
});

import type {
    NguHanh,
    ElementStrength,
    DivinationResult,
    Hexagram,
} from '../../src/types/maiHoa';

// ── US_MH_06: Ngũ Hành Interaction Tests ──────────────────────

describe('US_MH_06: getElementInteraction', () => {
    // ── Self-relations (Tỷ Hòa) ──────────────────────────────
    const allElements: NguHanh[] = ['Kim', 'Thủy', 'Mộc', 'Hỏa', 'Thổ'];

    test.each(allElements)('%s vs itself → Tỷ Hòa', (element) => {
        expect(getElementInteraction(element, element)).toBe('Tỷ Hòa');
    });

    // ── Sinh (generates) chain: Kim→Thủy→Mộc→Hỏa→Thổ→Kim ──
    const sinhPairs: [NguHanh, NguHanh][] = [
        ['Kim', 'Thủy'],
        ['Thủy', 'Mộc'],
        ['Mộc', 'Hỏa'],
        ['Hỏa', 'Thổ'],
        ['Thổ', 'Kim'],
    ];

    test.each(sinhPairs)('%s sinh %s → Sinh', (source, target) => {
        expect(getElementInteraction(source, target)).toBe('Sinh');
    });

    // ── Bị Sinh (is generated by) — inverse of Sinh ──────────
    const biSinhPairs: [NguHanh, NguHanh][] = [
        ['Thủy', 'Kim'],
        ['Mộc', 'Thủy'],
        ['Hỏa', 'Mộc'],
        ['Thổ', 'Hỏa'],
        ['Kim', 'Thổ'],
    ];

    test.each(biSinhPairs)('%s bị sinh bởi %s → Bị Sinh', (source, target) => {
        expect(getElementInteraction(source, target)).toBe('Bị Sinh');
    });

    // ── Khắc (controls) chain: Kim→Mộc→Thổ→Thủy→Hỏa→Kim ───
    const khacPairs: [NguHanh, NguHanh][] = [
        ['Kim', 'Mộc'],
        ['Mộc', 'Thổ'],
        ['Thổ', 'Thủy'],
        ['Thủy', 'Hỏa'],
        ['Hỏa', 'Kim'],
    ];

    test.each(khacPairs)('%s khắc %s → Khắc', (source, target) => {
        expect(getElementInteraction(source, target)).toBe('Khắc');
    });

    // ── Bị Khắc (is controlled by) — inverse of Khắc ────────
    const biKhacPairs: [NguHanh, NguHanh][] = [
        ['Mộc', 'Kim'],
        ['Thổ', 'Mộc'],
        ['Thủy', 'Thổ'],
        ['Hỏa', 'Thủy'],
        ['Kim', 'Hỏa'],
    ];

    test.each(biKhacPairs)('%s bị khắc bởi %s → Bị Khắc', (source, target) => {
        expect(getElementInteraction(source, target)).toBe('Bị Khắc');
    });

    // ── Total: 5×5 = 25 pairs are fully covered ──────────────
    test('complete 5×5 matrix coverage', () => {
        let count = 0;
        for (const a of allElements) {
            for (const b of allElements) {
                const result = getElementInteraction(a, b);
                expect(['Sinh', 'Khắc', 'Bị Sinh', 'Bị Khắc', 'Tỷ Hòa']).toContain(result);
                count++;
            }
        }
        expect(count).toBe(25);
    });
});

describe('US_MH_06: assessTheDung', () => {
    test('Dụng Sinh Thể (Cát)', () => {
        // Thủy (Thể) vs Kim (Dụng): Kim Sinh Thủy → Thể is generated = Bị Sinh
        const result = assessTheDung('Thủy', 'Kim');
        expect(result.relationship).toBe('Dụng Sinh Thể');
        expect(result.relationType).toBe('Bị Sinh');
        expect(result.verdict).toBe('Cát');
        expect(result.meaning).toContain('Được lợi');
    });

    test('Thể Sinh Dụng (Hung)', () => {
        // Kim (Thể) vs Thủy (Dụng): Kim Sinh Thủy → Thể expends energy = Sinh
        const result = assessTheDung('Kim', 'Thủy');
        expect(result.relationship).toBe('Thể Sinh Dụng');
        expect(result.relationType).toBe('Sinh');
        expect(result.verdict).toBe('Hung');
        expect(result.meaning).toContain('hao tổn');
    });

    test('Thể Khắc Dụng (Bình)', () => {
        // Kim (Thể) vs Mộc (Dụng): Kim Khắc Mộc → Thể controls
        const result = assessTheDung('Kim', 'Mộc');
        expect(result.relationship).toBe('Thể Khắc Dụng');
        expect(result.relationType).toBe('Khắc');
        expect(result.verdict).toBe('Bình');
        expect(result.meaning).toContain('khó nhọc');
    });

    test('Dụng Khắc Thể (Hung)', () => {
        // Mộc (Thể) vs Kim (Dụng): Mộc Bị Khắc bởi Kim → Dụng controls Thể
        const result = assessTheDung('Mộc', 'Kim');
        expect(result.relationship).toBe('Dụng Khắc Thể');
        expect(result.relationType).toBe('Bị Khắc');
        expect(result.verdict).toBe('Hung');
        expect(result.meaning).toContain('Đại hung');
    });

    test('Tỷ Hòa (Cát)', () => {
        const result = assessTheDung('Hỏa', 'Hỏa');
        expect(result.relationship).toBe('Thể Dụng Tỷ Hòa');
        expect(result.relationType).toBe('Tỷ Hòa');
        expect(result.verdict).toBe('Cát');
        expect(result.meaning).toContain('Bình hòa');
    });
});

// ── US_MH_07: Temporal Influence Tests ────────────────────────

describe('US_MH_07: getSeasonFromLunarMonth', () => {
    test.each([
        [1, 'Xuân'], [2, 'Xuân'], [3, 'Xuân'],
        [4, 'Hạ'], [5, 'Hạ'], [6, 'Hạ'],
        [7, 'Thu'], [8, 'Thu'], [9, 'Thu'],
        [10, 'Đông'], [11, 'Đông'], [12, 'Đông'],
    ] as [number, string][])('lunar month %i → %s', (month, expected) => {
        expect(getSeasonFromLunarMonth(month)).toBe(expected);
    });

    test('throws for invalid month 0', () => {
        expect(() => getSeasonFromLunarMonth(0)).toThrow(RangeError);
    });

    test('throws for invalid month 13', () => {
        expect(() => getSeasonFromLunarMonth(13)).toThrow(RangeError);
    });
});

describe('US_MH_07: getElementStrength', () => {
    // ── Kim element through all seasons ──────────────────────
    const kimSeasons: [number, ElementStrength][] = [
        [1, 'Tù'], [4, 'Tử'], [7, 'Vượng'], [10, 'Tướng'],
    ];

    test.each(kimSeasons)('Kim in month %i → %s', (month, expected) => {
        expect(getElementStrength('Kim', month)).toBe(expected);
    });

    // ── Mộc element through all seasons ─────────────────────
    const mocSeasons: [number, ElementStrength][] = [
        [1, 'Vượng'], [4, 'Tướng'], [7, 'Tử'], [10, 'Hưu'],
    ];

    test.each(mocSeasons)('Mộc in month %i → %s', (month, expected) => {
        expect(getElementStrength('Mộc', month)).toBe(expected);
    });

    // ── Hỏa element through all seasons ─────────────────────
    const hoaSeasons: [number, ElementStrength][] = [
        [1, 'Tướng'], [4, 'Vượng'], [7, 'Tù'], [10, 'Tử'],
    ];

    test.each(hoaSeasons)('Hỏa in month %i → %s', (month, expected) => {
        expect(getElementStrength('Hỏa', month)).toBe(expected);
    });

    // ── Thủy element through all seasons ────────────────────
    const thuySeasons: [number, ElementStrength][] = [
        [1, 'Hưu'], [4, 'Tù'], [7, 'Tướng'], [10, 'Vượng'],
    ];

    test.each(thuySeasons)('Thủy in month %i → %s', (month, expected) => {
        expect(getElementStrength('Thủy', month)).toBe(expected);
    });

    // ── Thổ element through all seasons ─────────────────────
    const thoSeasons: [number, ElementStrength][] = [
        [1, 'Tử'], [4, 'Tướng'], [7, 'Vượng'], [10, 'Tù'],
    ];

    test.each(thoSeasons)('Thổ in month %i → %s', (month, expected) => {
        expect(getElementStrength('Thổ', month)).toBe(expected);
    });

    // ── All 5 elements × 4 seasons = 20 total combinations ──
    test('exhaustive 5×4 coverage', () => {
        const elements: NguHanh[] = ['Kim', 'Thủy', 'Mộc', 'Hỏa', 'Thổ'];
        const representativeMonths = [1, 4, 7, 10]; // One per season
        let count = 0;
        for (const el of elements) {
            for (const m of representativeMonths) {
                const result = getElementStrength(el, m);
                expect(['Vượng', 'Tướng', 'Hưu', 'Tù', 'Tử']).toContain(result);
                count++;
            }
        }
        expect(count).toBe(20);
    });
});

describe('US_MH_07: describeTemporalInfluence', () => {
    test('returns Vietnamese description with element, season, and strength', () => {
        const desc = describeTemporalInfluence('Kim', 7); // Thu → Vượng
        expect(desc).toContain('Kim');
        expect(desc).toContain('Thu');
        expect(desc).toContain('Vượng');
    });

    test('weak element description', () => {
        const desc = describeTemporalInfluence('Thổ', 1); // Xuân → Tử
        expect(desc).toContain('Thổ');
        expect(desc).toContain('Xuân');
        expect(desc).toContain('Tử');
    });
});

// ── US_MH_08: Hexagram Meaning Lookup Tests ───────────────────

describe('US_MH_08: getHexagramMeaning', () => {
    test('extracts name, image, and meaning from a hexagram', () => {
        const hexagram: Hexagram = {
            id: 1,
            name: 'Thuần Càn',
            upper: 1,
            lower: 1,
            meaning: 'Trời trên trời, nguyên hanh lợi trinh.',
            image: 'Trời hành kiện, quân tử tự cường bất tức.',
        };
        const result = getHexagramMeaning(hexagram);
        expect(result.name).toBe('Thuần Càn');
        expect(result.image).toBe('Trời hành kiện, quân tử tự cường bất tức.');
        expect(result.meaning).toBe('Trời trên trời, nguyên hanh lợi trinh.');
    });

    test('returns exact references, no deep clone', () => {
        const hexagram: Hexagram = {
            id: 2,
            name: 'Thuần Khôn',
            upper: 8,
            lower: 8,
            meaning: 'Đất, nguyên hanh, lợi tẫn mã chi trinh.',
            image: 'Đất thế Khôn, quân tử dĩ hậu đức tải vật.',
        };
        const result = getHexagramMeaning(hexagram);
        expect(result).toEqual({
            name: 'Thuần Khôn',
            image: 'Đất thế Khôn, quân tử dĩ hậu đức tải vật.',
            meaning: 'Đất, nguyên hanh, lợi tẫn mã chi trinh.',
        });
    });
});

// ── Orchestrator: interpretDivination Tests ───────────────────

describe('Orchestrator: interpretDivination', () => {
    test('produces valid DivineReadingSummary shape', () => {
        // Use number-based divination for deterministic input
        const divResult = performNumberBasedDivination({ num1: 5, num2: 3 });
        const summary = interpretDivination(divResult, 2);

        // Shape checks
        expect(summary).toHaveProperty('overallVerdict');
        expect(summary).toHaveProperty('theDungAssessment');
        expect(summary).toHaveProperty('temporalInfluence');
        expect(summary).toHaveProperty('hexagramMeaning');
        expect(summary).toHaveProperty('detailedExplanation');
        expect(summary).toHaveProperty('elementBreakdown');

        // Verdict is a valid value
        expect(['Cát', 'Hung', 'Bình']).toContain(summary.overallVerdict);

        // TheDungAssessment has all fields
        expect(summary.theDungAssessment).toHaveProperty('relationship');
        expect(summary.theDungAssessment).toHaveProperty('relationType');
        expect(summary.theDungAssessment).toHaveProperty('meaning');
        expect(summary.theDungAssessment).toHaveProperty('verdict');

        // Temporal influence has all fields
        expect(summary.temporalInfluence).toHaveProperty('strength');
        expect(summary.temporalInfluence).toHaveProperty('description');

        // Hexagram meaning has all fields
        expect(summary.hexagramMeaning).toHaveProperty('name');
        expect(summary.hexagramMeaning).toHaveProperty('image');
        expect(summary.hexagramMeaning).toHaveProperty('meaning');

        // Detailed explanation is a non-empty string
        expect(typeof summary.detailedExplanation).toBe('string');
        expect(summary.detailedExplanation.length).toBeGreaterThan(0);

        // Element breakdown
        expect(summary.elementBreakdown).toHaveProperty('theElement');
        expect(summary.elementBreakdown).toHaveProperty('dungElement');
        expect(summary.elementBreakdown).toHaveProperty('relation');
    });

    test('time-based divination also produces valid summary', () => {
        const divResult = performTimeBasedDivination({
            yearChiIndex: 5,
            lunarMonth: 2,
            lunarDay: 5,
            hourChiIndex: 3,
        });
        const summary = interpretDivination(divResult, 2);
        expect(['Cát', 'Hung', 'Bình']).toContain(summary.overallVerdict);
        expect(typeof summary.detailedExplanation).toBe('string');
    });

    test('throws for invalid lunar month', () => {
        const divResult = performNumberBasedDivination({ num1: 1, num2: 1 });
        expect(() => interpretDivination(divResult, 0)).toThrow(RangeError);
        expect(() => interpretDivination(divResult, 13)).toThrow(RangeError);
    });

    test('Cát verdict when assessment is Cát and strength is Vượng', () => {
        // Mộc (Thể) in Xuân (month 1) = Vượng
        // We need Dụng to be Bị Sinh for Thể = Cát
        // If Thể = Mộc and Dụng = Thủy → Thủy sinh Mộc → Bị Sinh → Cát
        // Let's manually construct a DivinationResult
        const divResult = createMockDivinationResult('Mộc', 'Thủy');
        const summary = interpretDivination(divResult, 1);
        expect(summary.theDungAssessment.verdict).toBe('Cát');
        expect(summary.temporalInfluence.strength).toBe('Vượng');
        expect(summary.overallVerdict).toBe('Cát');
    });

    test('Hung verdict when assessment is Hung and strength is weak', () => {
        // Thổ (Thể) in Xuân (month 1) = Tử
        // Dụng = Mộc → Mộc khắc Thổ → Bị Khắc → Hung 
        const divResult = createMockDivinationResult('Thổ', 'Mộc');
        const summary = interpretDivination(divResult, 1);
        expect(summary.theDungAssessment.verdict).toBe('Hung');
        expect(summary.temporalInfluence.strength).toBe('Tử');
        expect(summary.overallVerdict).toBe('Hung');
    });

    test('Bình verdict when assessment is Hung but strength is strong', () => {
        // Kim (Thể) in Thu (month 7) = Vượng
        // Dụng = Thủy → Kim Sinh Thủy → Sinh → Hung
        const divResult = createMockDivinationResult('Kim', 'Thủy');
        const summary = interpretDivination(divResult, 7);
        expect(summary.theDungAssessment.verdict).toBe('Hung');
        expect(summary.temporalInfluence.strength).toBe('Vượng');
        expect(summary.overallVerdict).toBe('Bình');
    });

    test('Bình verdict when assessment is Cát but strength is weak', () => {
        // Kim (Thể) in Hạ (month 4) = Tử
        // Dụng = Thổ → Thổ Sinh Kim → Bị Sinh → Cát
        const divResult = createMockDivinationResult('Kim', 'Thổ');
        const summary = interpretDivination(divResult, 4);
        expect(summary.theDungAssessment.verdict).toBe('Cát');
        expect(summary.temporalInfluence.strength).toBe('Tử');
        expect(summary.overallVerdict).toBe('Bình');
    });

    test('detailed explanation includes hexagram name', () => {
        const divResult = performNumberBasedDivination({ num1: 3, num2: 7 });
        const summary = interpretDivination(divResult, 6);
        expect(summary.detailedExplanation).toContain(divResult.mainHexagram.name);
    });

    test('element breakdown matches divination elements', () => {
        const divResult = performNumberBasedDivination({ num1: 10, num2: 4 });
        const summary = interpretDivination(divResult, 9);
        expect(summary.elementBreakdown.theElement).toBe(divResult.elements.theElement);
        expect(summary.elementBreakdown.dungElement).toBe(divResult.elements.dungElement);
    });
});

// ── Integration Risk 2: Leap Month in Interpreter ─────────────

describe('Integration Risk 2: Leap Month in Interpreter', () => {
    test('leap month produces same seasonal strength as non-leap (same month number)', () => {
        // The engine treats leap month 4 identically to regular month 4.
        // Both map to the same season (Hạ) and produce the same strength.
        const divResult = performNumberBasedDivination({ num1: 5, num2: 3 });
        const summaryNormal = interpretDivination(divResult, 4);   // Regular month 4
        const summaryLeap = interpretDivination(divResult, 4);   // Leap month 4 (same value)

        expect(summaryNormal.temporalInfluence.strength).toBe(summaryLeap.temporalInfluence.strength);
        expect(summaryNormal.overallVerdict).toBe(summaryLeap.overallVerdict);
    });

    test('all 12 month values produce valid interpretations (no leap-only crash)', () => {
        const divResult = performNumberBasedDivination({ num1: 7, num2: 2 });
        for (let month = 1; month <= 12; month++) {
            const summary = interpretDivination(divResult, month);
            expect(['Cát', 'Hung', 'Bình']).toContain(summary.overallVerdict);
            expect(summary.temporalInfluence.description).toBeTruthy();
        }
    });
});

// ── Helpers ───────────────────────────────────────────────────

/**
 * Creates a mock DivinationResult with specific Thể/Dụng elements.
 * Uses Trigram IDs to match the desired elements.
 */
function createMockDivinationResult(
    theElement: NguHanh,
    dungElement: NguHanh,
): DivinationResult {
    // Find trigrams that match the desired elements
    const theTrigramId = findTrigramIdByElement(theElement);
    const dungTrigramId = findTrigramIdByElement(dungElement);

    // Moving line 1 → lower is Dụng, upper is Thể
    // So upper = Thể element, lower = Dụng element
    const mainHexagram: Hexagram = {
        id: 1,
        name: 'Test Hexagram',
        upper: theTrigramId,
        lower: dungTrigramId,
        meaning: 'Test meaning',
        image: 'Test image',
    };

    return {
        mainHexagram,
        mutualHexagram: mainHexagram,
        changedHexagram: mainHexagram,
        movingLine: 1,
        theTrigram: 'upper',
        dungTrigram: 'lower',
        elements: {
            theElement,
            dungElement,
        },
    };
}

/**
 * Finds the first trigram ID that has the specified Ngũ Hành element.
 */
function findTrigramIdByElement(element: NguHanh): number {
    const elementToTrigramId: Record<NguHanh, number> = {
        'Kim': 1,   // Càn = Kim
        'Hỏa': 3,   // Ly = Hỏa
        'Mộc': 4,   // Chấn = Mộc (actually Tốn is also Mộc)
        'Thủy': 6,  // Khảm = Thủy
        'Thổ': 8,   // Khôn = Thổ
    };
    return elementToTrigramId[element];
}
